# Generated by Django 4.2 on 2025-03-15 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=13)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('correo', models.TextField(max_length=100)),
                ('contrasena', models.TextField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('estadoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.estadousuario')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroTarjeta', models.BigIntegerField()),
                ('fechaCad', models.DateField()),
                ('cvv', models.IntegerField()),
                ('saldo', models.BigIntegerField()),
                ('tipoTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.tipotarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_bd/')),
                ('nombre', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=30)),
                ('material', models.TextField(max_length=30)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('estadoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.estadoproducto')),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=100)),
                ('fecha_compra', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.producto')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.tarjeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadArt', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.producto')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.usuario')),
            ],
        ),
    ]
