# Generated by Django 4.2 on 2025-05-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_compra',
            field=models.TextField(default='COMPRADO', max_length=50),
            preserve_default=False,
        ),
    ]
