# Generated by Django 4.2 on 2025-05-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_compra_estado_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('hora_agendada', models.TimeField()),
                ('observaciones', models.TextField(max_length=200)),
                ('estado_reparacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.estadoreparacion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.usuario')),
            ],
        ),
    ]
