# Generated by Django 4.2 on 2025-05-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0003_estadoreparacion_reparacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='estado_reparacion_id',
            new_name='estado_reparacion',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
