# Generated by Django 4.2 on 2025-05-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0004_rename_estado_reparacion_id_reparacion_estado_reparacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tarjeta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.tarjeta'),
            preserve_default=False,
        ),
    ]
