# Generated by Django 4.1.13 on 2025-06-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0005_usuario_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorasDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('hora_agendada', models.TimeField()),
                ('observaciones', models.TextField(max_length=200)),
                ('estado_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.estadohora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.usuario')),
            ],
        ),
    ]
