# Generated by Django 4.1.13 on 2025-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0006_estadohora_horasdisponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasdisponibles',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
