# Generated by Django 4.1.13 on 2025-06-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0007_alter_horasdisponibles_fecha_alter_reparacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horasdisponibles',
            name='usuario',
        ),
    ]
