# Generated by Django 4.1.13 on 2025-06-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0008_remove_horasdisponibles_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horasdisponibles',
            name='observaciones',
        ),
    ]
