# Generated by Django 4.1.13 on 2025-06-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0009_remove_horasdisponibles_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horasdisponibles',
            old_name='hora_agendada',
            new_name='hora',
        ),
    ]
