# Generated by Django 4.2 on 2025-06-09 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0010_rename_hora_agendada_horasdisponibles_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('porcentaje_visual', models.IntegerField(default=0)),
                ('orden', models.IntegerField(unique=True)),
                ('descripcion_cliente', models.TextField()),
            ],
            options={
                'verbose_name': 'Estado de Envío',
                'verbose_name_plural': 'Estados de Envío',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_entrega_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='nro_factura',
            field=models.TextField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.region')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='comuna_entrega',
            field=models.ForeignKey(blank=True, help_text='Comuna de destino para el envío a domicilio.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicicletas.comuna'),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado_seguimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bicicletas.estadoenvio'),
        ),
    ]
