# Generated by Django 4.2 on 2025-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0011_estadoenvio_region_compra_fecha_entrega_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nro_factura',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
