# Generated by Django 4.1.13 on 2025-06-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0013_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numeroFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_bd/'),
        ),
    ]
