# Generated by Django 4.1.13 on 2025-06-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0015_remove_producto_precio_producto_preciocompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numeroFactura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.proveedor'),
        ),
    ]
