# Generated by Django 4.1.13 on 2025-06-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0016_alter_producto_numerofactura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioCompra',
            new_name='precioCosto',
        ),
    ]
