# Generated by Django 4.1.13 on 2025-06-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0017_rename_preciocompra_producto_preciocosto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioCosto',
            new_name='precioCompra',
        ),
    ]
