# Generated by Django 4.1.13 on 2025-06-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0018_rename_preciocosto_producto_preciocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='utilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
