# Generated by Django 4.1.13 on 2025-06-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0019_alter_producto_utilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioVenta',
            new_name='precio',
        ),
    ]
