# Generated by Django 4.1.13 on 2025-06-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0020_rename_precioventa_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoObjeto', models.CharField(max_length=50)),
                ('objetoAfectado', models.CharField(max_length=200)),
                ('accion', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicletas.usuario')),
            ],
        ),
    ]
